### PR TITLE
Escape strings with string_escape rather than tojson

### LINKED ISSUE #3787: Crash when running greasemonkey with jinja <2.9
Debian stable packages a jinja 2.8, which crashes when trying to run any greasemonkey userscript.

```
Traceback (most recent call last):
  File "/home/jay/.local/lib/python3.5/site-packages/qutebrowser/browser/webengine/webview.py", line 355, in _inject_userjs
    _add_script(script, QWebEngineScript.DocumentReady)
  File "/home/jay/.local/lib/python3.5/site-packages/qutebrowser/browser/webengine/webview.py", line 343, in _add_script
    new_script.setSourceCode(script.code())
  File "/home/jay/.local/lib/python3.5/site-packages/qutebrowser/browser/greasemonkey.py", line 107, in code
    template = jinja.js_environment.get_template('greasemonkey_wrapper.js')
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "javascript/greasemonkey_wrapper.js", line 2, in template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 515, in _generate
    return generate(source, self, name, filename, defer_init=defer_init)
  File "/usr/lib/python3/dist-packages/jinja2/compiler.py", line 62, in generate
    generator.visit(node)
  File "/usr/lib/python3/dist-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/compiler.py", line 816, in visit_Template
    self.blockvisit(node.body, frame)
  File "/usr/lib/python3/dist-packages/jinja2/compiler.py", line 492, in blockvisit
    self.visit(node, frame)
  File "/usr/lib/python3/dist-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/compiler.py", line 1353, in visit_Output
    self.visit(argument, frame)
  File "/usr/lib/python3/dist-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/compiler.py", line 1565, in visit_Filter
    self.fail('no filter named %r' % node.name, node.lineno)
  File "/usr/lib/python3/dist-packages/jinja2/compiler.py", line 427, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: no filter named 'tojson'
```

This is because the tojson filter was added in 2.9. 

I'm going to give this a quick stab, but I haven't used jinja before so we'll see how that goes.
[cc: @toofar]

### PR DESCRIPTION
**Pull request by jgkamat**
This is a fairly naiive attempt to fix #3787.

instead of escaping js strings in jinja, I'm just escaping them with `javascript.string_escape`. 

Let me know if something seems off or if this seems bad for security reasons (?)

I verified this allows greasemonkey scripts (the ones that I tested at least) to run fine on jinja 2.8 from debian stable.

[cc: @toofar]

---
This change is [Reviewable](https://reviewable.io/reviews/qutebrowser/qutebrowser/3788)

### CODE REVIEW

File: qutebrowser/javascript/greasemonkey_wrapper.js [hunk 1]
```diff
@@ -1,13 +1,13 @@
 (function() {
-    const _qute_script_id = "__gm_" + {{ scriptName | tojson }};
+    const _qute_script_id = "__gm_" + "{{ scriptName }}";
```
Comment (toofar) [inline qutebrowser/javascript/greasemonkey_wrapper.js]: It seems the `" + "` from the middle of this can be removed now that it is being inserted as string-parsable chars rather than an actual json string with quotes on the ends. If you don't mind.

**Comment by toofar** [comment]
And I don't think there should be any additional security issues, I just used `tojson` [for escaping](https://beta.reviewable.io/reviews/qutebrowser/qutebrowser/3040#-Kvx4KIe9ehXUlaHJU0C) because it was there and I was already looking at the jinja docs (it was only ever passed python strings so it always actually made json strings).

File: qutebrowser/javascript/greasemonkey_wrapper.js (hunk 1 above)
Comment (The-Compiler) [reply qutebrowser/javascript/greasemonkey_wrapper.js]: I'll fix this up while merging.

**Comment by The-Compiler** [comment]
I'm somewhat surprised you're only the second person to run into this (there was a crash report two weeks ago but I didn't understand what was happening). Thanks!
